.TH "psub" 1 "Thu May 26 2016" "Version 2.3.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
\fBpsub\fP -- perform process substitution 

.PP
.SS "Synopsis"
.PP
.nf

COMMAND1 ( COMMAND2 | \fBpsub\fP [-f] [-s SUFFIX])
.fi
.PP
.SS "Description"
Posix shells feature a syntax that is a mix between command substitution and piping, called process substitution\&. It is used to send the output of a command into the calling command, much like command substitution, but with the difference that the output is not sent through commandline arguments but through a named pipe, with the filename of the named pipe sent as an argument to the calling program\&. \fCpsub\fP combined with a regular command substitution provides the same functionality\&.
.PP
If the \fC-f\fP or \fC--file\fP switch is given to \fCpsub\fP, \fCpsub\fP will use a regular file instead of a named pipe to communicate with the calling process\&. This will cause \fCpsub\fP to be significantly slower when large amounts of data are involved, but has the advantage that the reading process can seek in the stream\&.
.PP
If the \fC-s\fP or \fC---suffix\fP switch is given, \fCpsub\fP will append SUFFIX to the filename\&.
.SS "Example"
.PP
.nf

diff (sort a\&.txt | \fBpsub\fP) (sort b\&.txt | \fBpsub\fP)
  shows the difference between the sorted versions of files \fCa\&.txt\fP and \fCb\&.txt\fP\&.
.fi
.PP
.PP
.PP
.nf
\fBsource\fP-highlight -f esc (cpp main\&.c | \fBpsub\fP -s \&.c)
  highlights \fCmain\&.c\fP after preprocessing as a C source\&.
.fi
.PP
 
